### ISSUE TITLE
Could you please provide some hint about solving the problems?

### ISSUE THREAD

**Issue by guoquan** [summer666max/Leetcode#10]
Let's move to the next topic.

Please provide a report to explain the solution, proof necessary lemma, or describe any trick to play. You don't need to fill them for past questions and solutions. Just for the future ones are good.

You might want to provide them in some `.md` documents, however you have too much of them already. No one can find them easily. Consider other tools on GitHub, `issue`, `pr`, `actions`, `projects`, `wiki`, or anything I didn't know. Make sure they are searchable so reader can find a report with GitHub search.

It is easy already, try to do it in English.

**Comment by guoquan** [comment]
Any plan on this?

**Comment by guoquan** [comment]
@summer666max 👀

**Comment by ZeaoZhang** [comment]
>收到

**Comment by ZeaoZhang** [comment]
实在抱歉，耽搁了这么久，下次不会了
