### ISSUE TITLE
test result

### ISSUE THREAD

**Issue by Adversityovo** [summer666max/Leetcode#9]

**Comment by Adversityovo** [comment]
> _No description provided._

**Comment by guoquan** [comment]
Yeah you having fun 👀

**Comment by ZeaoZhang** [comment]
> Yeah you having fun 👀

INDEED 😓 . Yesterday, I went to my grandmother's house. When I came back, I lay in bed and suddenly thought that leetcode hadn't been done yet. So I got up again 😂 .
